// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_notification.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAlertNotification = `-- name: CreateAlertNotification :exec
INSERT INTO alert_notifications (alert_id,user_id)
VALUES ($1, $2)
ON CONFLICT (alert_id, user_id) DO NOTHING
`

type CreateAlertNotificationParams struct {
	AlertID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) CreateAlertNotification(ctx context.Context, arg CreateAlertNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createAlertNotification, arg.AlertID, arg.UserID)
	return err
}

const getPendingAlertsForUser = `-- name: GetPendingAlertsForUser :many
SELECT
    an.id,
    an.alert_id,
    an.status,
    an.user_id,
    u.name AS creator_name
FROM alert_notifications an
JOIN alerts a
    ON an.alert_id = a.id
JOIN users u
    ON a.user_id = u.id
WHERE an.user_id = $1
AND an.status = 'pending'
`

type GetPendingAlertsForUserRow struct {
	ID          uuid.UUID
	AlertID     uuid.UUID
	Status      string
	UserID      uuid.UUID
	CreatorName sql.NullString
}

func (q *Queries) GetPendingAlertsForUser(ctx context.Context, userID uuid.UUID) ([]GetPendingAlertsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingAlertsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingAlertsForUserRow
	for rows.Next() {
		var i GetPendingAlertsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.Status,
			&i.UserID,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationAccepted = `-- name: MarkNotificationAccepted :exec
UPDATE alert_notifications
SET status = 'accepted'
WHERE alert_id = $1
AND user_id = $2
`

type MarkNotificationAcceptedParams struct {
	AlertID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) MarkNotificationAccepted(ctx context.Context, arg MarkNotificationAcceptedParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationAccepted, arg.AlertID, arg.UserID)
	return err
}
