// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_notification.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAlertNotification = `-- name: CreateAlertNotification :exec
INSERT INTO alert_notifications (alert_id,user_id)
VALUES ($1, $2)
ON CONFLICT (alert_id, user_id) DO NOTHING
`

type CreateAlertNotificationParams struct {
	AlertID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) CreateAlertNotification(ctx context.Context, arg CreateAlertNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createAlertNotification, arg.AlertID, arg.UserID)
	return err
}

const getPendingAlertsForUser = `-- name: GetPendingAlertsForUser :one
SELECT id, alert_id, user_id, status, created_at
FROM alert_notifications
WHERE user_id = $1
AND status = 'pending'
`

func (q *Queries) GetPendingAlertsForUser(ctx context.Context, userID uuid.UUID) (AlertNotification, error) {
	row := q.db.QueryRowContext(ctx, getPendingAlertsForUser, userID)
	var i AlertNotification
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
