// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_responses.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countAcceptedUsers = `-- name: CountAcceptedUsers :one
SELECT COUNT(*)
FROM alert_responses
WHERE alert_id = $1 AND status = 'accepted'
`

func (q *Queries) CountAcceptedUsers(ctx context.Context, alertID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAcceptedUsers, alertID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlertResponse = `-- name: CreateAlertResponse :exec
INSERT INTO alert_responses (alert_id, user_id, status)
VALUES ($1, $2, 'accepted')
`

type CreateAlertResponseParams struct {
	AlertID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) CreateAlertResponse(ctx context.Context, arg CreateAlertResponseParams) error {
	_, err := q.db.ExecContext(ctx, createAlertResponse, arg.AlertID, arg.UserID)
	return err
}

const getAcceptedUsers = `-- name: GetAcceptedUsers :many
SELECT user_id
FROM alert_responses
WHERE alert_id = $1 AND status = 'accepted'
`

func (q *Queries) GetAcceptedUsers(ctx context.Context, alertID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getAcceptedUsers, alertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserAcceptedAlert = `-- name: HasUserAcceptedAlert :one
SELECT EXISTS(
    SELECT 1
    FROM alert_responses
    WHERE alert_id = $1
    AND user_id = $2
)
`

type HasUserAcceptedAlertParams struct {
	AlertID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) HasUserAcceptedAlert(ctx context.Context, arg HasUserAcceptedAlertParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasUserAcceptedAlert, arg.AlertID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
