// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (user_id, latitude, longitude, status)
VALUES ($1, $2, $3, 'active')
RETURNING id, user_id, latitude, longitude, status, created_at
`

type CreateAlertParams struct {
	UserID    uuid.UUID
	Latitude  float64
	Longitude float64
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRowContext(ctx, createAlert, arg.UserID, arg.Latitude, arg.Longitude)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
