// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    room_id,
    sender_id,
    content
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, room_id, sender_id, content, created_at
`

type CreateMessageParams struct {
	RoomID   uuid.UUID
	SenderID uuid.UUID
	Content  string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.RoomID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT
    m.id,
    m.room_id,
    m.sender_id,
    u.name AS sender_name,
    m.content,
    m.created_at
FROM messages m
JOIN users u
    ON m.sender_id = u.id
WHERE m.id = $1
`

type GetMessageByIDRow struct {
	ID         uuid.UUID
	RoomID     uuid.UUID
	SenderID   uuid.UUID
	SenderName sql.NullString
	Content    string
	CreatedAt  time.Time
}

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (GetMessageByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.SenderName,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomMessages = `-- name: GetRoomMessages :many
SELECT
    m.id,
    m.room_id,
    m.sender_id,
    u.name AS sender_name,
    m.content,
    m.created_at
FROM messages m
JOIN users u
    ON m.sender_id = u.id
WHERE m.room_id = $1
ORDER BY m.created_at ASC
`

type GetRoomMessagesRow struct {
	ID         uuid.UUID
	RoomID     uuid.UUID
	SenderID   uuid.UUID
	SenderName sql.NullString
	Content    string
	CreatedAt  time.Time
}

func (q *Queries) GetRoomMessages(ctx context.Context, roomID uuid.UUID) ([]GetRoomMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomMessages, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomMessagesRow
	for rows.Next() {
		var i GetRoomMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.SenderName,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isRoomMember = `-- name: IsRoomMember :one
SELECT EXISTS(
    SELECT 1
    FROM room_members
    WHERE room_id = $1
    AND user_id = $2
)
`

type IsRoomMemberParams struct {
	RoomID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) IsRoomMember(ctx context.Context, arg IsRoomMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isRoomMember, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
