// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (
    id,
    room_id,
    sender_id,
    content
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateMessageParams struct {
	ID       uuid.UUID
	RoomID   uuid.UUID
	SenderID uuid.UUID
	Content  string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.RoomID,
		arg.SenderID,
		arg.Content,
	)
	return err
}

const getRecentRoomMessages = `-- name: GetRecentRoomMessages :many
SELECT id, room_id, sender_id, content, created_at
FROM messages
WHERE room_id = $1
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) GetRecentRoomMessages(ctx context.Context, roomID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getRecentRoomMessages, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomMessages = `-- name: GetRoomMessages :many
SELECT id, room_id, sender_id, content, created_at
FROM messages
WHERE room_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetRoomMessages(ctx context.Context, roomID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getRoomMessages, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
