// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Alert struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Latitude  float64
	Longitude float64
	Status    string
	CreatedAt time.Time
}

type AlertResponse struct {
	AlertID     uuid.UUID
	UserID      uuid.UUID
	Status      string
	RespondedAt sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}

type UserLocation struct {
	UserID    uuid.UUID
	Latitude  float64
	Longitude float64
	UpdatedAt time.Time
}
