// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addRoomMember = `-- name: AddRoomMember :exec
INSERT INTO room_members(room_id, user_id)
VALUES($1, $2)
`

type AddRoomMemberParams struct {
	RoomID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error {
	_, err := q.db.ExecContext(ctx, addRoomMember, arg.RoomID, arg.UserID)
	return err
}

const createRoom = `-- name: CreateRoom :exec
INSERT INTO rooms(id, alert_id)
VALUES($1, $2)
`

type CreateRoomParams struct {
	ID      uuid.UUID
	AlertID uuid.UUID
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.ExecContext(ctx, createRoom, arg.ID, arg.AlertID)
	return err
}

const getRoomInfo = `-- name: GetRoomInfo :one
SELECT
    r.id,
    r.alert_id,
    u.name AS creator_name,
    a.latitude,
    a.longitude
FROM rooms r
JOIN alerts a
    ON r.alert_id = a.id
JOIN users u
    ON a.user_id = u.id
WHERE r.id = $1
`

type GetRoomInfoRow struct {
	ID          uuid.UUID
	AlertID     uuid.UUID
	CreatorName sql.NullString
	Latitude    float64
	Longitude   float64
}

func (q *Queries) GetRoomInfo(ctx context.Context, id uuid.UUID) (GetRoomInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getRoomInfo, id)
	var i GetRoomInfoRow
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.CreatorName,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getRoomMembers = `-- name: GetRoomMembers :many
SELECT user_id
FROM room_members
WHERE room_id = $1
`

func (q *Queries) GetRoomMembers(ctx context.Context, roomID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRooms = `-- name: GetUserRooms :many
SELECT
    r.id AS room_id,
    u.name AS creator_name,
    a.latitude,
    a.longitude
FROM room_members rm
JOIN rooms r
    ON rm.room_id = r.id
JOIN alerts a
    ON r.alert_id = a.id
JOIN users u
    ON a.user_id = u.id
WHERE rm.user_id = $1
`

type GetUserRoomsRow struct {
	RoomID      uuid.UUID
	CreatorName sql.NullString
	Latitude    float64
	Longitude   float64
}

func (q *Queries) GetUserRooms(ctx context.Context, userID uuid.UUID) ([]GetUserRoomsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRoomsRow
	for rows.Next() {
		var i GetUserRoomsRow
		if err := rows.Scan(
			&i.RoomID,
			&i.CreatorName,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
