// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_locations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserLocations = `-- name: GetUserLocations :many
SELECT user_id,latitude,longitude
FROM user_locations
WHERE latitude BETWEEN $1 - 0.01 AND $1 + 0.01
AND longitude BETWEEN $2 - 0.01 AND $2 + 0.01
`

type GetUserLocationsParams struct {
	Column1 interface{}
	Column2 interface{}
}

type GetUserLocationsRow struct {
	UserID    uuid.UUID
	Latitude  float64
	Longitude float64
}

func (q *Queries) GetUserLocations(ctx context.Context, arg GetUserLocationsParams) ([]GetUserLocationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserLocations, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserLocationsRow
	for rows.Next() {
		var i GetUserLocationsRow
		if err := rows.Scan(&i.UserID, &i.Latitude, &i.Longitude); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserLocations = `-- name: UpdateUserLocations :exec
INSERT INTO user_locations(user_id,latitude,longitude,updated_at)
VALUES(
    $1,
    $2,
    $3,
    NOW()
)
ON CONFLICT (user_id)
DO UPDATE SET
latitude = EXCLUDED.latitude,
longitude = EXCLUDED.longitude,
updated_at = NOW()
`

type UpdateUserLocationsParams struct {
	UserID    uuid.UUID
	Latitude  float64
	Longitude float64
}

func (q *Queries) UpdateUserLocations(ctx context.Context, arg UpdateUserLocationsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLocations, arg.UserID, arg.Latitude, arg.Longitude)
	return err
}
