// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_locations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserLocationByUserID = `-- name: GetUserLocationByUserID :one
SELECT user_id,latitude,longitude
FROM user_locations
WHERE user_id = $1
`

type GetUserLocationByUserIDRow struct {
	UserID    uuid.UUID
	Latitude  float64
	Longitude float64
}

func (q *Queries) GetUserLocationByUserID(ctx context.Context, userID uuid.UUID) (GetUserLocationByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserLocationByUserID, userID)
	var i GetUserLocationByUserIDRow
	err := row.Scan(&i.UserID, &i.Latitude, &i.Longitude)
	return i, err
}

const getUserLocations = `-- name: GetUserLocations :many
SELECT user_id, latitude, longitude
FROM user_locations
WHERE latitude BETWEEN $1::float8 - 0.01 AND $1::float8 + 0.01
AND longitude BETWEEN $2::float8 - 0.01 AND $2::float8 + 0.01
`

type GetUserLocationsParams struct {
	Lat float64
	Lng float64
}

type GetUserLocationsRow struct {
	UserID    uuid.UUID
	Latitude  float64
	Longitude float64
}

func (q *Queries) GetUserLocations(ctx context.Context, arg GetUserLocationsParams) ([]GetUserLocationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserLocations, arg.Lat, arg.Lng)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserLocationsRow
	for rows.Next() {
		var i GetUserLocationsRow
		if err := rows.Scan(&i.UserID, &i.Latitude, &i.Longitude); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserLocations = `-- name: UpdateUserLocations :exec
INSERT INTO user_locations(user_id,latitude,longitude,updated_at)
VALUES(
    $1,
    $2,
    $3,
    NOW()
)
ON CONFLICT (user_id)
DO UPDATE SET
latitude = EXCLUDED.latitude,
longitude = EXCLUDED.longitude,
updated_at = NOW()
`

type UpdateUserLocationsParams struct {
	UserID    uuid.UUID
	Latitude  float64
	Longitude float64
}

func (q *Queries) UpdateUserLocations(ctx context.Context, arg UpdateUserLocationsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLocations, arg.UserID, arg.Latitude, arg.Longitude)
	return err
}
